import Navbar from "@/components/Navbar";
import Library from "@/components/Library";
import Head from "next/head";
import Image from "next/image";

export default function Blogs() {
  return (
    <>
      <Head>
        <title>spu-metaverse</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="../public/image/element/Mask Group 251.png" />
      </Head>
      <div className="bg-[#f2f2f2]">
        <Navbar />
        <section className="absolute w-full">
          <Image
            className="w-full h-full -translate-y-[-30%] md:-translate-y-[-5%] lg:-translate-y-[6%] 3xl:-translate-y-[5%]"
            src="/image/4-1@2x.png"
            alt=""
            width={1000}
            height={1000}
            quality={100}
          />
        </section>
        <Library />
        <section className="absolute w-full inset-0 -translate-y-[-90%] md:-translate-y-[-80%] lg:-translate-y-[-80%] xl:-translate-y-[-70%]  3xl:-translate-y-[-58%]">
          <Image
            className="w-full 3xl:h-[45rem] 3xl:-translate-y-[-45%]"
            src="/image/5-1@2x.png"
            alt=""
            width={1000}
            height={1000}
            quality={100}
          />
        </section>
        <section className="absolute left-0 translate-y-[79%]  z-10">
          <div
            className="coral01 md:w-[8rem] md:h-[9rem] lg:w-[10rem] 
          lg:h-[13rem] xl:w-[15rem] xl:h-[15rem] 3xl:h-[19.6rem] 3xl:w-[23rem] justify-end  z-50 "
          ></div>
        </section>
        <section className="absolute right-0 -translate-y-[45%]  z-10">
          <div className="tree md:h-[29rem] md:w-56 lg:h-[42rem] lg:w-[24rem]   xl:h-[48rem] xl:w-[24rem]  3xl:h-[63.8rem] 3xl:w-[35rem] justify-end  z-50 "></div>
        </section>
        <section className="absolute right-0 -translate-y-[0%]  md:-translate-y-[45%]  z-10">
          <div className="tree w-96  h-[40rem]  mb:h-[42rem] md:h-[29rem] md:w-56 lg:h-[42rem] lg:w-[24rem]   xl:h-[48rem] xl:w-[24rem]  3xl:h-[63.8rem] 3xl:w-[35rem] justify-end  z-50 "></div>
        </section>
      </div>
    </>
  );
}
