import Head from "next/head";
import Main from "@/components/Main";
import Navbar2 from "@/components/Navbar2";
import About from "@/components/About";
import Main_News from "@/components/Main_News";
import FAQs from "@/components/FAQs";
import Contact from "@/components/Contact";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>spu-metaverse</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Navbar2 />
        <Main />
        <section className="absolute left-0 md:translate-y-[15%] 3xl:-translate-y-[15%]  z-10">
          <div className="coral02 w-40 h-48 md:w-40 md:h-48 lg:w-56 lg:h-56 xl:w-80 xl:h-96 3xl:h-[50rem] 3xl:w-[40rem] justify-end  z-50 "></div>
        </section>
        <About />
        <section className="absolute left-0 md:translate-y-[15%] lg:translate-y-[30%] 3xl:translate-y-[-30%]  z-10">
          <div className="dimon01 w-40 h-48 md:w-40 md:h-48  xl:w-64 xl:h-64 3xl:h-[30rem] 3xl:w-[25rem] justify-end  z-50 "></div>
        </section>
        <section className="absolute md:w-full -z-50">
          <Image
            className=" w-[40rem] h-[40rem] -translate-y-[53%] md:w-full md:h-full md:-translate-y-[32%] lg:-translate-y-[35%] 3xl:-translate-y-[44%]"
            src="/image/4-1@2x.png"
            alt=""
            width={1000}
            height={1000}
            quality={100}
          />
        </section>
        <section className="absolute right-0 -translate-y-[40%] md:-translate-y-[5%] xl:-translate-y-[20%]  3xl:-translate-y-[35%]  z-10">
          <div className="tree2 w-40 h-56 md:w-40 md:h-56 lg:w-48 lg:h-72 xl:w-72 xl:h-[40rem] 3xl:h-[65rem] 3xl:w-[35rem] justify-end  z-50 "></div>
        </section>
        <Main_News />
        <section className="absolute right-0 -translate-y-[45%]  z-10">
          <div className="mus01 w-60 h-[18rem]  md:h-[65rem] md:w-[35rem] justify-end  z-50 "></div>
        </section>
        <FAQs />
        <section className="absolute left-0 -translate-y-[60%]  z-10">
          <div className="star01 w-60  h-[18rem] md:h-[30rem] md:w-[25rem] justify-end  z-50 "></div>
        </section>
        <Contact />
        <section className="absolute left-0 translate-y-[79%]  z-10">
          <div
            className=" coral01 md:w-[8rem] md:h-[9rem] lg:w-[10rem] 
          lg:h-[13rem] xl:w-[15rem] xl:h-[15rem] 3xl:h-[19.6rem] 3xl:w-[23rem] justify-end  z-50 "
          ></div>
        </section>
        <section className="absolute right-0 -translate-y-[0%]  md:-translate-y-[45%]  z-10">
          <div className="tree w-96  h-[40rem]  mb:h-[42rem] md:h-[29rem] md:w-56 lg:h-[42rem] lg:w-[24rem]   xl:h-[48rem] xl:w-[24rem]  3xl:h-[63.8rem] 3xl:w-[35rem] justify-end  z-50 "></div>
        </section>
      </div>
    </>
  );
}
