import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header";
import News from "@/components/News";
import Navbar from "@/components/Navbar";
const inter = Inter({ subsets: ["latin"] });

export default function NewsPage() {
  return (
    <>
      <Head>
        <title>spu-metaverse</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="../public/image/element/Mask Group 251.png" />
      </Head>
      <div className="bg-[#f2f2f2]">
        <Navbar />
        <Header />
        <News />
        <section className="absolute left-0 translate-y-[79%]  z-10">
          <div
            className="coral01 md:w-[8rem] md:h-[9rem] lg:w-[10rem] 
          lg:h-[13rem] xl:w-[15rem] xl:h-[15rem] 3xl:h-[19.6rem] 3xl:w-[23rem] justify-end  z-50 "
          ></div>
        </section>
        <section className="absolute right-0 -translate-y-[0%]  md:-translate-y-[45%]  z-10">
          <div className="tree w-96  h-[40rem]  mb:h-[42rem] md:h-[29rem] md:w-56 lg:h-[42rem] lg:w-[24rem]   xl:h-[48rem] xl:w-[24rem]  3xl:h-[63.8rem] 3xl:w-[35rem] justify-end  z-50 "></div>
        </section>
      </div>
    </>
  );
}
